# Generated by Django 4.1.7 on 2023-05-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autre_Cotisation',
            fields=[
                ('id_cotisation', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiaire', models.CharField(max_length=30)),
                ('nom_cotisant', models.CharField(max_length=30)),
                ('montant_attendu', models.FloatField()),
                ('montant_verser', models.FloatField()),
                ('reste', models.FloatField()),
                ('date', models.DateField()),
                ('type_cotisation', models.CharField(blank=True, choices=[('Epargne', 'Epargne')], max_length=60)),
                ('autre_type', models.CharField(blank=True, max_length=60)),
                ('interet', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cotisation_Sinistre',
            fields=[
                ('id_cotisation', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiaire', models.CharField(max_length=30)),
                ('nom_cotisant', models.CharField(max_length=30)),
                ('montant_attendu', models.FloatField()),
                ('montant_verser', models.FloatField()),
                ('reste', models.FloatField()),
                ('date', models.DateField()),
                ('type_sinistre', models.CharField(blank=True, choices=[('Maladie', 'Maladie'), ('Accident', 'Accident'), ('Deuil', 'Deuil'), ('Accouchement', 'Accouchement')], max_length=60)),
                ('autre_type', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enregistrement_Emprunt',
            fields=[
                ('id_enregistrement', models.AutoField(primary_key=True, serialize=False)),
                ('emprunteur', models.CharField(max_length=50)),
                ('montant_attendu', models.FloatField()),
                ('montant_verser', models.FloatField()),
                ('reste', models.FloatField()),
                ('interet', models.FloatField()),
                ('date_remboursement', models.DateField()),
                ('raison_emprunt', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id_infos', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiaire', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mutuelle',
            fields=[
                ('id_mutuelle', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('abbreviation', models.CharField(max_length=30)),
                ('nom_association', models.CharField(max_length=50)),
                ('date_creation', models.DateField()),
                ('statut_association', models.CharField(max_length=100)),
                ('reglement_interieur', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_users', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('noms', models.CharField(max_length=20)),
                ('prenoms', models.CharField(max_length=20)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('pays', models.CharField(choices=[('CMR', 'Cameroun')], max_length=20)),
                ('ville', models.CharField(choices=[('YDE', 'Yaounde'), ('DLA', 'Douala'), ('GAR', 'Garoua'), ('MAR', 'Maroua'), ('BER', 'Bertoua'), ('EBOL', 'Ebolowa'), ('BUEA', 'Buea'), ('NGA', 'Ngaoundere'), ('BAM', 'Bamenda'), ('BAF', 'Bafoussam')], max_length=20)),
                ('date_creation', models.DateField()),
                ('statut', models.CharField(choices=[('TRES', 'TRESORIER'), ('SECR', 'SECRETAIRE'), ('ASSIS TRES', 'ASSISTANT TRESORIER'), ('REPORT', 'REPORTEUR')], max_length=30)),
                ('e_mail', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Infos_Cotisation',
            fields=[
                ('infos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.infos')),
                ('type_cotisation', models.CharField(blank=True, choices=[('Maladie', 'Maladie'), ('Accident', 'Accident'), ('Deuil', 'Deuil'), ('Accouchement', 'Accouchement')], max_length=30)),
                ('autre_type', models.CharField(blank=True, max_length=60)),
            ],
            bases=('crud.infos',),
        ),
        migrations.CreateModel(
            name='Infos_Emprunt',
            fields=[
                ('infos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.infos')),
                ('montant', models.FloatField()),
                ('raison', models.CharField(max_length=50)),
                ('date_remboursement', models.DateField()),
                ('interet', models.FloatField()),
            ],
            bases=('crud.infos',),
        ),
        migrations.CreateModel(
            name='Infos_Sinistre',
            fields=[
                ('infos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.infos')),
                ('type_sinistre', models.CharField(choices=[('Maladie', 'Maladie'), ('Accident', 'Accident'), ('Deuil', 'Deuil'), ('Accouchement', 'Accouchement')], max_length=30)),
                ('autre_type', models.CharField(blank=True, max_length=60)),
            ],
            bases=('crud.infos',),
        ),
        migrations.CreateModel(
            name='Preuv_Remb_Empr',
            fields=[
                ('id_preuve', models.AutoField(primary_key=True, serialize=False)),
                ('noms_membre', models.CharField(max_length=50)),
                ('montant_attendu', models.FloatField()),
                ('montant_verser', models.FloatField()),
                ('date', models.DateField()),
                ('justificatifs', models.FileField(upload_to='')),
                ('reste', models.FloatField()),
                ('interet', models.FloatField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preuv_Cotisation',
            fields=[
                ('id_preuve', models.AutoField(primary_key=True, serialize=False)),
                ('noms_membre', models.CharField(max_length=50)),
                ('montant_attendu', models.FloatField()),
                ('montant_verser', models.FloatField()),
                ('date', models.DateField()),
                ('justificatifs', models.FileField(upload_to='')),
                ('nature_cotisation', models.CharField(max_length=20)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preuv_Cotis_Sinistre',
            fields=[
                ('id_preuve', models.AutoField(primary_key=True, serialize=False)),
                ('noms_membre', models.CharField(max_length=50)),
                ('montant_attendu', models.FloatField()),
                ('montant_verser', models.FloatField()),
                ('date', models.DateField()),
                ('justificatifs', models.FileField(upload_to='')),
                ('nature_sinistre', models.CharField(max_length=20)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demande_Emprunt',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiaire', models.CharField(max_length=30)),
                ('montant', models.FloatField()),
                ('interet', models.FloatField()),
                ('date_remboursement', models.DateField()),
                ('motif', models.CharField(max_length=80)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
            ],
        ),
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('id_annonce', models.AutoField(primary_key=True, serialize=False)),
                ('objet', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=300)),
                ('destinataire', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
            ],
        ),
    ]
